const { Schema,model } = require('mongoose');

const VentaSchema = Schema({
    pedidos:[
        {
            type: Schema(
                {
                    productos:{
                        type:Array,
                        require:true
                    },
                    total:{
                        type:Number,
                        require:true
                    },
                    tienda:{
                        type:String,
                        require:true
                    },
                    repartidor:{
                        type:String,
                        require:true
                    },
                    entregado:{
                        type:Boolean,
                        require:true
                    },
                    imagen:{
                        type:String,
                        require:true
                    },
                    confirmado:{
                        type:Boolean,
                        require:true
                    },
                    proceso_iniciado:{
                        type:Boolean,
                        require:true
                    },
                    proceso_finalizado:{
                        type:Boolean,
                        require:true
                    },
                    pagado:{
                        type:Boolean,
                        require:true
                    },
                    preparado:{
                        type:Boolean,
                        require:true
                    },
                    enviado:{
                        type:Boolean,
                        require:true
                    },
                    entregado_repartidor:{
                        type:Boolean,
                        require:true
                    },
                    entregado:{
                        type:Boolean,
                        require:true
                    },
                    ubicacion:{
                        type:Object,
                        require:true
                    },
                    ubicacion:{
                        type:Object,
                        require:true
                    },
                    direccion:{
                        type:String,
                        require:true
                    },
                    punto_venta:{
                        type:String,
                        require:true
                    },
                    usuario:{
                        type:Object,
                        require:true
                    },
                    efectivo:{
                        type:Boolean,
                        require:true
                    },
                    tiempo_espera:{
                        type:Number,
                        require:true
                    },
                    confirmacion_tiempo:{
                        type:Date,
                        require:false
                    },
                    entrega_repartidor_tiempo:{
                        type:Date,
                        require:false
                    },
                    codigo_repartidor:{
                        type:String,
                        require:true
                    },
                    id_venta:{
                        type:Schema.Types.ObjectId,
                        require:true
                    }
                },
                { timestamps: true }
            )
        }
    ],
    total:{
        type:Number,
        require:true
    },
    efectivo:{
        type:Boolean,
        require:true
    },
    metodoPago:{
        type:Object,
        require:false
    },
    usuario:{
        type:Schema.Types.ObjectId,
        require:true
    },
    envio:{
        type:Number,
        require:true,
    },
    servicio:{
        type:Number,
        require:true,
    },
    envioPromo:{
        type:Number,
        require:true,
    },
    direccion:{
        type:Object,
        require:true
    }
    
},{
    timestamps:true
});

VentaSchema.method('toJson',function(){
    const{__v,id,...object} = this.toObject();
    return object;
});

module.exports = model('Ventas',VentaSchema);